import type { FastifyPluginAsyncZod } from 'fastify-type-provider-zod';
import { authRoutes } from './auth.js';
import { healthRoutes } from './health.js';
import { orgRoutes } from './org.js';
import { attendantRoutes } from './attendants.js';
import { recipientRoutes } from './recipients.js';
import { recipientSubresourceRoutes } from './recipient-subresources.js';
import { userRoutes } from './users.js';
import { paymentCodeRoutes } from './payment-codes.js';
import { scheduleRoutes } from './schedule.js';
import { patternRoutes } from './patterns.js';
import { leaveRoutes } from './leaves.js';
import { mobileRoutes } from './mobile.js';
import { auditRoutes } from './audit.js';

export const registerRoutes: FastifyPluginAsyncZod = async (app) => {
  await app.register(healthRoutes);
  await app.register(authRoutes);
  await app.register(orgRoutes);
  await app.register(attendantRoutes);
  await app.register(recipientRoutes);
  await app.register(recipientSubresourceRoutes);
  await app.register(userRoutes);
  await app.register(paymentCodeRoutes);
  await app.register(scheduleRoutes);
  await app.register(patternRoutes);
  await app.register(leaveRoutes);
  await app.register(mobileRoutes);
  await app.register(auditRoutes);
};
